version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    depends_on:
      - db
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:8000 boosting_site_backend.wsgi:application
    
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run build && npm run preview -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000/api
    stdin_open: true  # Necesario para algunos apps de React
    tty: true        # Mantiene el contenedor activo
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: mi_base
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: clave
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
